/*
	Main Civilization Configuration
	Author: Baconace
	Template by MC
*/

-----------------------------------------------
-- Types
-----------------------------------------------

INSERT INTO	Types
			(Type,							Kind					)
VALUES		('CIVILIZATION_BCA_THAYLENAH',		'KIND_CIVILIZATION'		);
		
-----------------------------------------------
-- Civilizations
-----------------------------------------------

INSERT INTO	Civilizations
			(
			CivilizationType,
			Name,
			Description,
			Adjective,
			StartingCivilizationLevelType,
			RandomCityNameDepth,
			Ethnicity
			)

VALUES		(
			'CIVILIZATION_BCA_THAYLENAH', --CivilizationType
			'LOC_CIVILIZATION_BCA_THAYLENAH_NAME', -- Name
			'LOC_CIVILIZATION_BCA_THAYLENAH_DESCRIPTION', -- Description
			'LOC_CIVILIZATION_BCA_THAYLENAH_ADJECTIVE', -- Adjective
			'CIVILIZATION_LEVEL_FULL_CIV', -- StartingCivilizationLevelType
			6, -- RandomCityNameDepth
			'ETHNICITY_MEDIT' -- Ethnicity
			);

-----------------------------------------------
-- NamedSeas
-----------------------------------------------

INSERT OR REPLACE INTO NamedSeas
		(NamedSeaType,						Name										)
VALUES	('NAMED_SEA_LONGBROW',	'LOC_NAMED_SEA_LONGBROW'		),
		('NAMED_SEA_SOUTHERN_DEPTHS', 'LOC_NAMED_SEA_SOUTHERN_DEPTHS');

-----------------------------------------------
-- NamedSeaCivilizations
-----------------------------------------------

INSERT INTO NamedSeaCivilizations
		(CivilizationType,			NamedSeaType					)
VALUES	('CIVILIZATION_BCA_THAYLENAH',	'NAMED_SEA_LONGBROW'	),
		('CIVILIZATION_BCA_THAYLENAH',	'NAMED_SEA_SOUTHERN_DEPTHS'	);

-----------------------------------------------
-- CityNames
-----------------------------------------------

INSERT INTO	CityNames
		(CivilizationType,			CityName						)
VALUES	('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_1'		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_2'		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_3'		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_4'		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_5'		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_6'		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_7'		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_8'		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_9'		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_10'		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_11'		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_12'		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_13'		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_14'		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_15'		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_16'		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_17'		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_18'		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_19'		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITY_NAME_BCA_THAYLENAH_20'		);
		
-----------------------------------------------
-- CivilizationCitizenNames
-----------------------------------------------

INSERT INTO	CivilizationCitizenNames
		(CivilizationType,			CitizenName,						Female	)
VALUES	('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_MALE_1',		0 		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_MALE_2',		0 		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_MALE_3',		0 		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_MALE_4',		0 		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_MALE_5',		0 		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_MALE_6',		0 		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_MALE_7',		0 		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_MALE_8',		0 		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_MALE_9',		0 		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_MALE_10',	0 		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_FEMALE_1',	1 		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_FEMALE_2',	1 		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_FEMALE_3',	1 		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_FEMALE_4',	1 		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_FEMALE_5',	1 		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_FEMALE_6',	1 		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_FEMALE_7',	1 		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_FEMALE_8',	1 		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_FEMALE_9',	1 		),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CITIZEN_BCA_THAYLENAH_FEMALE_10',	1 		);

-----------------------------------------------
-- CivilizationInfo
-----------------------------------------------

INSERT INTO	CivilizationInfo
		(CivilizationType,			Header,						Caption,								SortIndex	)
VALUES	('CIVILIZATION_BCA_THAYLENAH',	'LOC_CIVINFO_LOCATION',		'LOC_CIVINFO_BCA_THAYLENAH_LOCATION',		10			),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CIVINFO_SIZE',			'LOC_CIVINFO_BCA_THAYLENAH_SIZE',			20			),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CIVINFO_POPULATION',	'LOC_CIVINFO_BCA_THAYLENAH_POPULATION',		30			),
		('CIVILIZATION_BCA_THAYLENAH',	'LOC_CIVINFO_CAPITAL',		'LOC_CIVINFO_BCA_THAYLENAH_CAPITAL',			40			);
		
-----------------------------------------------
-- Start Bias
---------------------------------------------

INSERT INTO	StartBiasTerrains
		(CivilizationType,			TerrainType,			Tier	)
VALUES	('CIVILIZATION_BCA_THAYLENAH',	'TERRAIN_COAST',		1		);

INSERT INTO	StartBiasResources
		(CivilizationType,			ResourceType,			Tier	)
VALUES	('CIVILIZATION_BCA_THAYLENAH',	'RESOURCE_NITER',		4		),
		('CIVILIZATION_BCA_THAYLENAH',	'RESOURCE_FISH',		2		),
		('CIVILIZATION_BCA_THAYLENAH',	'RESOURCE_CRABS',		3		);